# Use NGINX official image as the base image
FROM nginx

# Copy the index file to the default web server directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 for web service
EXPOSE 80
